server:
  port: 8090

spring:
  application:
    name: service-producer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0


    datasource:
     url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
     username: root
     password: 123456
     driver-class-name: com.mysql.cj.jdbc.Driver
     continueOnError: true



eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

#是否开启swagger文档 true-开启  false-关闭
swagger:
  enable: true

feign:
  httpclient:
    enabled: true

#打印执行的sql
logging:
  level:
    com:
      zdzc:
        dao: debug


  pattern:
    console: %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
  path: ${spring.application.name}
  config: classpath:logger.xml


mybatis:
  mapper-locations: classpath:com/zdzc/dao/mapper/*.xml
