server:
  port: 8099


spring:
  application:
    name: service-consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  main:
    allow-bean-definition-overriding: true


eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

#开启Hystrix
feign:
  hystrix:
    enabled: false


#是否开启swagger文档 true-开启  false-关闭
swagger:
  enable: true