#server:
#  port: 9411
#spring:
#  application:
#    name: zipkin-service
#
#
#
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    driver-class-name:
#    continueOnError: true
#
#zipkin:
#  storage:
#    type: mysql
#
#sleuth:
#  enabled: false
#
#eureka:
#  client:
#    service-url:
#      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

server:
  port: 9411
spring:
  application:
    name: zipkin-service
  main:
    allow-bean-definition-overriding: true

  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/



management:
  metrics:
    web:
      server:
        auto-time-requests: false
